name: Update Current Branch

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: imagina/basequasar-app
          token:  ${{ secrets.DEPLOY_ADMIN_THEME }}

      - name: Initialize submodules
        run: git submodule update --init --remote

      - name: Github Credentials
        run: |
          git config --global user.name "Imagina Actions Bot"
          git config --global user.email "carlosdevia@imaginacolombia.com"
          git config --global url."https://${{ secrets.DEPLOY_ADMIN_THEME }}@github.com/".insteadOf "https://github.com/"
      
      - name: Update Version
        run: |
          git fetch --no-recurse-submodules
          git submodule foreach --recursive git fetch          
          git checkout v2.x
          git merge --allow-unrelated-histories origin/v2.x
          git submodule foreach --recursive git checkout v2.x
          git submodule foreach --recursive git merge --allow-unrelated-histories origin/v2.x
          git add .
          git commit -m "Realease" || true
          npm version patch
          git push origin v2.x

      - name: Merge release to input branch
        run: |
          git checkout v2.x
          git merge --allow-unrelated-histories origin/v2.x
          git submodule foreach --recursive git checkout v2.x
          git submodule foreach --recursive git merge --allow-unrelated-histories origin/v2.x
          git submodule foreach --recursive git push -u origin v2.x
          git push origin v2.x
